### ISSUE TITLE
right panel map annotations for a Value

### ISSUE THREAD

**Issue by will-moore** [ome/omero-mapr#67]
As reported https://forum.image.sc/t/omero-mapr-questions/50843, this is 1 of the 2 errors from "second issue" and reproduced on IDR:
When a mapr Value is selected in the Tree (see screenshot) mapr tries to load Annotations for it in the right panel.

![Screenshot 2021-04-01 at 10 36 43](https://user-images.githubusercontent.com/900055/113275426-b7d86180-92d6-11eb-819b-70a929a8c84e.png)

However, the webclient rendering of these map annotations expects each to have a `link` (to show what object each is linked to:

```
# webclient mapanns_underscore.html

                 <!-- If single object show e.g. Image ID: (slice ImageI -> Image) -->
                        <b><%= ann.link.parent.class.slice(0, ann.link.parent.class.length-1) %>
                            ID:</b> <%= ann.link.parent.id %><br />
```

and this isn't loaded by mapr, so we get the error above.

**Comment by joshmoore** [comment]
Certainly don't object to the safety check, but it'd be good to understand why the parent is unloaded.
